# Generated by Django 3.2.8 on 2021-11-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211031_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
