# Generated by Django 3.2.9 on 2021-11-11 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(default=None, max_length=100)),
                ('type', models.CharField(choices=[('meat', 'Meat'), ('carbohydrate', 'Carbohydrate'), ('vegetable', 'Vegetable'), ('condiment', 'Condiment'), ('fruit', 'Fruit'), ('other', 'Other')], default='other', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DontNeed', models.ManyToManyField(blank=True, related_name='dontNeed', to='recipe.ingredient')),
                ('Have', models.ManyToManyField(blank=True, related_name='Have', to='recipe.ingredient')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='usersearch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('menu', models.CharField(default=None, max_length=100)),
                ('ingredient_unit', models.TextField(blank=True)),
                ('HowToDo', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('dessert', 'Dessert'), ('meat', 'Meat'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('ocovegen', 'Ocovegen'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], default=None, max_length=100)),
                ('price', models.FloatField(default=None, null=True)),
                ('calorie', models.IntegerField(default=None, null=True)),
                ('ingredientInmenu', models.ManyToManyField(blank=True, related_name='ingredientInrecipe', to='recipe.ingredient')),
                ('like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('confirm', models.CharField(choices=[('no', 'No'), ('confirm', 'Confirm')], default='no', max_length=10)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=None, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField()),
                ('time', models.TimeField(default=None)),
                ('name', models.CharField(default=None, max_length=100)),
                ('bankaccount', models.CharField(default=None, max_length=4)),
                ('confirm', models.CharField(choices=[('no', 'No'), ('confirm', 'Confirm')], default='no', max_length=10)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='menu_order', to='recipe.recipe')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='userbuy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipe.recipe')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Addrecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankaccount', models.CharField(default=None, max_length=20)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('menu', models.CharField(default=None, max_length=100)),
                ('ingredient_unit', models.TextField(blank=True)),
                ('HowToDo', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('dessert', 'Dessert'), ('meat', 'Meat'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('ocovegen', 'Ocovegen'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], default=None, max_length=100)),
                ('confirm', models.CharField(choices=[('no', 'No'), ('confirm', 'Confirm')], default='no', max_length=10)),
                ('price', models.IntegerField(default=None, null=True)),
                ('calorie', models.IntegerField(default=None, null=True)),
                ('ingredientHave', models.ManyToManyField(blank=True, related_name='ingredientHave', to='recipe.ingredient')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
