# Generated by Django 3.0 on 2021-11-06 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(default=None, max_length=100)),
                ('type', models.CharField(choices=[('meat', 'Meat'), ('carbohydrate', 'Carbohydrate'), ('vegetable', 'Vegetable'), ('condiment', 'Condiment'), ('fruit', 'Fruit'), ('other', 'Other')], default='other', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('menu', models.CharField(default=None, max_length=100)),
                ('ingredient_unit', models.TextField(blank=True)),
                ('HowToDo', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('dessert', 'Dessert'), ('meat', 'Meat'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('ocovegen', 'Ocovegen'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], default=None, max_length=100)),
                ('price', models.IntegerField(default=None, null=True)),
                ('calorie', models.IntegerField(default=None, null=True)),
                ('ingredientInmenu', models.ManyToManyField(blank=True, related_name='ingredientInrecipe', to='recipe.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_by', models.CharField(default=None, max_length=100)),
                ('body', models.TextField(default=None)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipe.recipe')),
            ],
        ),
    ]
