# Generated by Django 3.0 on 2021-11-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_by',
        ),
    ]
