# Generated by Django 3.2.9 on 2021-11-07 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addrecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankaccount', models.CharField(default=None, max_length=20)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('menu', models.CharField(default=None, max_length=100)),
                ('ingredient_unit', models.TextField(blank=True)),
                ('HowToDo', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('dessert', 'Dessert'), ('meat', 'Meat'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('ocovegen', 'Ocovegen'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], default=None, max_length=100)),
                ('price', models.IntegerField(default=None, null=True)),
                ('calorie', models.IntegerField(default=None, null=True)),
                ('ingredientHave', models.ManyToManyField(blank=True, related_name='ingredientHave', to='recipe.ingredient')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
