# Generated by Django 3.0 on 2021-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('meat', 'Meat'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('oco vegen', 'Ovo'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], max_length=100),
        ),
    ]
