# Generated by Django 3.2.9 on 2021-11-08 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0002_addrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecipe',
            name='confirm',
            field=models.CharField(choices=[('no', 'No'), ('confirm', 'Confirm')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DontNeed', models.ManyToManyField(blank=True, related_name='dontNeed', to='recipe.ingredient')),
                ('Have', models.ManyToManyField(blank=True, related_name='Have', to='recipe.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=None, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(default=None, max_length=100)),
                ('bankaccount', models.CharField(default=None, max_length=4)),
                ('confirm', models.CharField(choices=[('no', 'No'), ('confirm', 'Confirm')], default='no', max_length=10)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
