# Generated by Django 3.0 on 2021-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20211027_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('meat', 'Meat'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('oco vegen', 'Ovo'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], default='normal', max_length=100),
        ),
    ]
