# Generated by Django 3.2.9 on 2021-11-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_addrecipe_ingredienthave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='type',
            field=models.CharField(choices=[('dessert', 'Dessert'), ('meat', 'Meat'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('ovovegen', 'Ovovegen'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('dessert', 'Dessert'), ('meat', 'Meat'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('ovovegen', 'Ovovegen'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], default=None, max_length=100),
        ),
    ]
