# Generated by Django 3.2.6 on 2021-11-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20211119_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
