# Generated by Django 3.0 on 2021-10-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20211027_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(choices=[('meat', 'Meat'), ('carbohydrate', 'Carbohydrate'), ('vegetable', 'Vegetable'), ('condiment', 'Condiment'), ('fruit', 'Fruit'), ('other', 'Other')], default='other', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='menu',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredientInmenu',
            field=models.ManyToManyField(blank=True, related_name='ingredientInrecipe', to='recipe.ingredient'),
        ),
    ]
