# Generated by Django 3.0 on 2021-10-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20211027_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='menu1',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
