# Generated by Django 3.0 on 2021-10-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_recipe_menu1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='menu1',
        ),
        migrations.AddField(
            model_name='recipe',
            name='HowToDo',
            field=models.CharField(default=None, max_length=50000),
        ),
    ]
