# Generated by Django 3.0 on 2021-10-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20211030_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='HowToDo',
        ),
    ]
