# Generated by Django 3.0 on 2021-10-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_recipe_howtodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient_unit',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('meat', 'Meat'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('oco vegen', 'Oco'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], default='normal', max_length=100),
        ),
    ]
