# Generated by Django 3.0 on 2021-10-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_auto_20211030_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calorie',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('meat', 'Meat'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('oco vegen', 'Oco'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], default='normal', max_length=100),
        ),
    ]
