# Generated by Django 3.0 on 2021-11-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_auto_20211104_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('dessert', 'Dessert'), ('meat', 'Meat'), ('halal', 'Halal'), ('beverag', 'Beverag'), ('ocovegen', 'Ocovegen'), ('vegetarian', 'Vegy'), ('appetizer', 'Appetizer')], default=None, max_length=100),
        ),
    ]
