# Generated by Django 3.0 on 2021-11-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_auto_20211105_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='status',
        ),
    ]
